const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(__dirname, 'apps/**/src/**/!(*.stories|*.spec).{ts,html}'),
    join(__dirname, 'libs/**/src/**/!(*.stories|*.spec).{ts,html}'),
    join(__dirname, 'plugins/**/src/**/!(*.stories|*.spec).{ts,html}'),
  ],
  important: true,
  theme: {
    borderRadius: {
      0: '0rem',
      0.5: '0.125rem',
      1: '0.25rem',
      2: '0.5rem',
      3: '0.75rem',
      4: '1rem',
      5: '1.25rem',
      6: '1.5rem',
      7: '1.75rem',
      8: '2rem',
      9: '2.25rem',
      10: '2.5rem',
      11: '2.75rem',
      12: '3rem',
      13: '3.25rem',
      14: '3.5rem',
      15: '3.75rem',
      16: '4rem',
      20: '5rem',
      full: '999999px',
    },
    boxShadow: {
      0: '0px 0px 0px rgba(0, 0, 0, 0), 0px 0px 0px 0px rgba(0, 0, 0, 0)',
      1: '0px 1px 2px rgba(0, 0, 0, 0.3), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)',
      2: '0px 1px 2px rgba(0, 0, 0, 0.3), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)',
      3: '0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px rgba(0, 0, 0, 0.3)',
      4: '0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px rgba(0, 0, 0, 0.3)',
      5: '0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px rgba(0, 0, 0, 0.3)',
    },
    extend: {
      zIndex: {
        1: 1,
        5: 5,
      },
      screens: {
        // mobile ranges from 0px to lg screen
        mobile: { min: '0px', max: '1024px' },
        // desktop ranges from lg to ...
        desktop: '1024px',
      },
      lineHeight: {
        0: 0,
      },
      backdropBlur: {
        xs: '1px',
      },
      fontSize: {
        xs: '0.75rem',
        '2xs': '0.625rem',
        '3xs': '0.5rem',
      },
      spacing: {
        inherit: 'inherit',
        13: '3.25rem',
        14: '3.5rem',
        15: '3.75rem',
        17: '4.25rem',
        18: '4.5rem',
        19: '4.75rem',
        21: '5.25rem',
        22: '5.5rem',
        23: '5.75rem',
      },
            colors: {
        inherit: 'inherit',
        primary: {
          DEFAULT: 'var(--primary-default)',
          container: 'var(--primary-container)',
          'on-container': 'var(--primary-on-container)',
          inverse: 'var(--primary-inverse)',
          fixed: 'var(--primary-fixed)',
          'fixed-dim': 'var(--primary-fixed-dim)',
          'on-fixed': 'var(--primary-on-fixed)',
          'on-fixed-variant': 'var(--primary-on-fixed-variant)',
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          400: 'var(--primary-400)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
          800: 'var(--primary-800)',
          900: 'var(--primary-900)',
        },
        secondary: {
          DEFAULT: 'var(--secondary-default)',
          container: 'var(--secondary-container)',
          'on-container': 'var(--secondary-on-container)',
          inverse: 'var(--secondary-inverse)',
          fixed: 'var(--secondary-fixed)',
          'fixed-dim': 'var(--secondary-fixed-dim)',
          'on-fixed': 'var(--secondary-on-fixed)',
          'on-fixed-variant': 'var(--secondary-on-fixed-variant)',
          50: 'var(--secondary-50)',
          100: 'var(--secondary-100)',
          200: 'var(--secondary-200)',
          300: 'var(--secondary-300)',
          400: 'var(--secondary-400)',
          500: 'var(--secondary-500)',
          600: 'var(--secondary-600)',
          700: 'var(--secondary-700)',
          800: 'var(--secondary-800)',
          900: 'var(--secondary-900)',
        },
        tertiary: {
          DEFAULT: 'var(--tertiary-default)',
          container: 'var(--tertiary-container)',
          'on-container': 'var(--tertiary-on-container)',
          inverse: 'var(--tertiary-inverse)',
          fixed: 'var(--tertiary-fixed)',
          'fixed-dim': 'var(--tertiary-fixed-dim)',
          'on-fixed': 'var(--tertiary-on-fixed)',
          'on-fixed-variant': 'var(--tertiary-on-fixed-variant)',
          50: 'var(--tertiary-50)',
          100: 'var(--tertiary-100)',
          200: 'var(--tertiary-200)',
          300: 'var(--tertiary-300)',
          400: 'var(--tertiary-400)',
          500: 'var(--tertiary-500)',
          600: 'var(--tertiary-600)',
          700: 'var(--tertiary-700)',
          800: 'var(--tertiary-800)',
          900: 'var(--tertiary-900)',
        },
        error: {
          DEFAULT: 'var(--error-default)',
          container: 'var(--error-container)',
          'on-container': 'var(--error-on-container)',
          50: 'var(--error-50)',
          100: 'var(--error-100)',
          200: 'var(--error-200)',
          300: 'var(--error-300)',
          400: 'var(--error-400)',
          500: 'var(--error-500)',
          600: 'var(--error-600)',
          700: 'var(--error-700)',
          800: 'var(--error-800)',
          900: 'var(--error-900)',
        },
        surface: {
          DEFAULT: 'var(--surface)',
          dim: 'var(--surface-dim)',
          bright: 'var(--surface-bright)',
          'container-lowest': 'var(--surface-container-lowest)',
          'container-low': 'var(--surface-container-low)',
          'container-high': 'var(--surface-container-high)',
          'container-highest': 'var(--surface-container-highest)',
          container: 'var(--surface-container)',
          'on-container': 'var(--surface-on-container)',
          on: 'var(--surface-on)',
          variant: 'var(--surface-variant)',
          'variant-dim': 'var(--surface-variant-dim)',
          'on-variant': 'var(--surface-on-variant)',
          inverse: 'var(--surface-inverse)',
          'on-inverse': 'var(--surface-on-inverse)',
        },
        outline: {
          DEFAULT: 'var(--outline)',
          variant: 'var(--outline-variant)',
        },
        background: 'var(--background)',
      }
    },
  },
  plugins: [
    require('./libs/base/src/configs/tailwind'),
    // require('@cac/base/tailwind'),
  ],
};
