import { inject } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { MatIconRegistry } from '@angular/material/icon';

const baseIcons = [
  'close',
  'nav',
  'chevron-left',
  'chevron-right',
  'plus',
  'edit',
  'excel-file',
  'filter',
  'filter-filled',
  'sort',
  'sort-up',
  'sort-down',
  'trash',
  'dropdown',
  'print',
  'numeric-up',
  'numeric-down',
  'search',
  'user',
  'password',
  'logout',
  'calendar',
  'time',
  'bag',
  'branch',
  'building',
  'database',
  'field-edit',
  'id',
  'info',
  'role',
  'security',
  'settings',
  'station',
  'ticket',
  'truck',
  'users',
  'paper-details',
  'weight',
  'wrench',
  'location-check',
  'sort-indicator',
  'cargo',
  'stopwatch',
  'hashtag',
  'check',
  'sync',
  'server',
  'rfid-tag',
  'question-circle',
  'connection',
  'ai',
  'power',
  'code',
  'company',
  'edit-box',
  'license-plate',
  'monitor',
  'print-alt',
  'transport',
  'trash-alt',
  'sync-warn',
  'list',
  'cloud',
  'database-filled',
  'ticket-filled',
  'security-filled',
  'paper-details-filled',
  'settings-filled',
  'arrow-right',
  'info-circle',
  'filter-chips',
  'filter-name',
  'filter-address',
  'filter-box',
  'filter-branch',
  'filter-company',
  'filter-connection',
  'filter-date',
  'filter-driving-license',
  'filter-duration',
  'filter-entezamat',
  'filter-gear',
  'filter-ghabz',
  'filter-hashtag',
  'filter-id-no',
  'filter-in-out',
  'filter-ip-address',
  'filter-item',
  'filter-license-plate',
  'filter-personel-code',
  'filter-phone',
  'filter-rfid',
  'filter-role',
  'filter-station-name',
  'filter-text',
  'filter-time',
  'filter-toggle',
  'filter-vehicle',
  'filter-weight',
  'camera',
  'cars',
  'cars-filled',
  'plate',
  'traffic-report',
  'traffic-report-active',
  'paper',
  'toggle',
  'house',
  'house-active',
  'phone',
  'landline-phone',
  'location',
  'route',
  'key',
  'eye',
  'eye-slash',
  'traffic',
  'dashboard',
  'dashboard-filled',
  'reports',
  'reports-filled',
  'delete',
  'add',
  'save',
  'play',
  'car',
  'error',
];

export function registerIcons(icons?: string[]) {
  const sanitizer = inject(DomSanitizer);
  const iconRegistry = inject(MatIconRegistry);

  for (const icon of baseIcons) {
    iconRegistry.addSvgIcon(icon, sanitizer.bypassSecurityTrustResourceUrl(`./assets/base/icons/${icon}.svg`));
  }

  for (const icon of icons ?? []) {
    iconRegistry.addSvgIcon(icon, sanitizer.bypassSecurityTrustResourceUrl(`./assets/icons/${icon}.svg`));
  }
}
